from .align_init import instantiate_model_by_align
from .focus_init import instantiate_model_by_focus
from .mean_init import instantiate_model_by_mean
from .merge_init import instantiate_model_by_merge
from .random_init import instantiate_model_by_random
